import React from 'react'
import {
  Activity,
  AlarmClock,
  Award,
  Anchor,
  Bandage,
  Beef,
  BicepsFlexed,
  Blend,
  Bot,
  BookKey,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  CircleDotDashed,
  CircleHelp,
  CloudLightning,
  CloudRain,
  Clover,
  Coins,
  Crown,
  Dices,
  Drama,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  EyeOff,
  Feather,
  FileText,
  FlaskConical,
  Flame,
  Footprints,
  Gem,
  Ghost,
  Hammer,
  History,
  Hourglass,
  KeyRound,
  Landmark,
  Layers,
  Lightbulb,
  LockKeyhole,
  Moon,
  MoonStar,
  Mountain,
  MoveUpRight,
  Medal,
  NotebookTabs,
  Music,
  Orbit,
  Radar,
  ScanEye,
  ScrollText,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Swords,
  Telescope,
  TriangleAlert,
  Trophy,
  UserRound,
  WandSparkles,
  Wand,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Catálogo de iconos genéricos disponibles para los elementos. El admin
// selecciona una clave de esta lista; nada de recursos de franquicias.
export const ELEMENT_ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'alarm-clock': AlarmClock,
  'award': Award,
  'bandage': Bandage,
  'beef': Beef,
  'eye': Eye,
  'eye-off': EyeOff,
  'scan-eye': ScanEye,
  'coins': Coins,
  'user-round': UserRound,
  'radar': Radar,
  'clover': Clover,
  'moon-star': MoonStar,
  'medal': Medal,
  'sparkles': Sparkles,
  'anchor': Anchor,
  'biceps-flexed': BicepsFlexed,
  'blend': Blend,
  'bot': Bot,
  'book-key': BookKey,
  'book-open': BookOpen,
  'brain': Brain,
  'briefcase-business': BriefcaseBusiness,
  'circle-dot-dashed': CircleDotDashed,
  'circle-help': CircleHelp,
  'cloud-lightning': CloudLightning,
  'cloud-rain': CloudRain,
  'crown': Crown,
  'dices': Dices,
  'drama': Drama,
  'droplets': Droplets,
  'dumbbell': Dumbbell,
  'ear': Ear,
  'feather': Feather,
  'file-text': FileText,
  'flask-conical': FlaskConical,
  'flame': Flame,
  'footprints': Footprints,
  'gem': Gem,
  'ghost': Ghost,
  'history': History,
  'hammer': Hammer,
  'hourglass': Hourglass,
  'key-round': KeyRound,
  'landmark': Landmark,
  'layers': Layers,
  'lightbulb': Lightbulb,
  'lock-keyhole': LockKeyhole,
  'moon': Moon,
  'mountain': Mountain,
  'move-up-right': MoveUpRight,
  'notebook-tabs': NotebookTabs,
  'music': Music,
  'orbit': Orbit,
  'scroll-text': ScrollText,
  'shield': Shield,
  'skull': Skull,
  'star': Star,
  'sun': Sun,
  'swords': Swords,
  'telescope': Telescope,
  'triangle-alert': TriangleAlert,
  'trophy': Trophy,
  'wand-sparkles': WandSparkles,
  'wand': Wand,
  'waves': Waves,
  'wind': Wind,
  'zap': Zap,
}

export const ICON_KEYS = Object.keys(ELEMENT_ICONS)

export function IconoElemento({
  iconKey,
  className,
}: {
  iconKey: string
  className?: string
}) {
  const Icon = ELEMENT_ICONS[iconKey] ?? Sparkles
  return <Icon className={className} aria-hidden="true" />
}
