import type { BuilderCardState } from '../domain/schema'

// A new card is created server-side, so every seed must remain valid enough for
// the schema while still showing the editor which fields need replacing.
export const NEW_CARD_SEEDS: Partial<Record<BuilderCardState['type'], Partial<BuilderCardState>>> = {
  Character: { name: 'Nueva carta' },
  Artifact: { name: 'Nuevo artefacto' },
  Cover: { coverTitle: 'Nueva portada', coverPartNum: '1' },
  'Full Image Cover': { fullCoverTitle: 'Nueva portada' },
  Tier: {},
  Pathway: {},
  'Tier Explanation': { tierExplanationText: 'Nueva explicacion' },
  'General Explanation': {
    generalExplanationTitle: 'Nueva explicacion',
    generalExplanationText: 'Nueva explicacion',
  },
  'Simple Explanation': { simpleExplanationText: 'Write the explanation here.' },
  'Pathway Explanation': {
    pathwayExplanationTitle: 'Nueva explicacion',
    pathwayExplanationText: 'Nueva explicacion',
  },
  Breakdown: {
    breakdownTitle: 'Nuevo concepto',
    breakdownDoes: 'Que hace.',
    breakdownDoesNot: 'Que no hace.',
    breakdownEdgeText: 'El matiz clave.',
  },
  Map: {
    mapTitle: 'Nuevo mapa',
    mapEntriesText: 'Etiqueta -> Valor',
  },
  'Tarot Member': {
    tarotMemberName: 'New member',
    tarotMemberTitle: 'The Unknown',
    tarotMemberDescription: 'What the Club sees.',
    tarotMemberDetailText: 'What is actually happening.',
  },
  'Corruption File': {
    corruptionIncident: 'New incident',
    corruptionExplanation: 'What happened.',
    corruptionReaction: 'What the fandom did with it.',
  },
  'Ritual Logic': {
    ritualVariant: 'Chain',
    ritualSequenceName: 'New sequence',
    ritualText: 'What the ritual requires.',
    ritualSurvival: 'What the ritual helps the aspirant survive.',
    ritualPreparation: 'What the ritual rehearses before the new powers arrive.',
  },
}

export const DEFAULT_STATE: BuilderCardState = {
  type: 'Character',
  name: 'Yhwach',
  path: 'Wheel of Fortune',
  seq: 0,
  hasSecond: false,
  path2: 'Fool',
  seq2: 9,
  power: 'King of Angels',
  grade: '0',
  mod: '',
  dom: 'None',
  image: null,
  coverImage1: null,
  coverImage2: null,
  coverTitle: 'Fate',
  coverPartNum: '1',
  fullCoverImage: null,
  fullCoverTitle: '',
  tierPath: 'Fool',
  tierSeq: null,
  tierRank: 'S',
  tierText: '',
  tierFooterText: '',
  tierBackgroundImage: null,
  pathwayCardPath: 'Fool',
  pathwayCardSeq: null,
  pathwayCardText: '',
  pathwayCardFooterText: '',
  pathwayCardBackgroundImage: null,
  explanationPath: null,
  tierExplanationText: '',
  tierExplanationBackgroundImage: null,
  generalExplanationTitle: '',
  generalExplanationText: '',
  generalExplanationSequence: null,
  generalExplanationBackgroundImage: null,
  simpleExplanationText: '',
  pathwayExplanationPath: 'Fool',
  pathwayExplanationTitle: '',
  pathwayExplanationText: '',
  pathwayExplanationBackgroundImage: null,
  breakdownKicker: '',
  breakdownTitle: '',
  breakdownDoes: '',
  breakdownDoesNot: '',
  breakdownEdgeLabel: 'Edge',
  breakdownEdgeText: '',
  breakdownBackgroundImage: null,
  mapTitle: '',
  mapEntriesText: '',
  mapFooterText: '',
  mapBackgroundImage: null,
  mapPathway: null,
  tarotMemberVariant: 'Portrait',
  tarotMemberName: '',
  tarotMemberTitle: '',
  tarotMemberDescription: '',
  tarotMemberDetailLabel: 'Club function',
  tarotMemberDetailText: '',
  tarotMemberFooterText: '',
  tarotMemberPathway: null,
  tarotMemberAccentColor: null,
  tarotMemberImage: null,
  corruptionVariant: 'Warning',
  corruptionIncident: '',
  corruptionCaseLabel: 'Normal explanation',
  corruptionExplanation: '',
  corruptionReactionLabel: 'Fandom reaction',
  corruptionReaction: '',
  corruptionFooterText: '',
  corruptionLevel: 'Severe',
  corruptionShowIncidentNumber: false,
  corruptionAccentColor: '#d84a4a',
  corruptionImage: null,
  ritualPathway: 'Fool',
  ritualSequence: 5,
  ritualVariant: 'Chain',
  ritualSequenceName: '',
  ritualText: '',
  ritualSurvival: '',
  ritualPreparation: '',
  ritualCertainty: 'Mixed',
  ritualUncertainty: '',
  ritualFooterText: '',
  ritualBackgroundImage: null,
  backgroundOpacity: 65,
}

export const VIDEO_FORMATS = ['card', 'shorts'] as const
